media:
  input: "assets/images"
  output: "assets/images"

content:
  - type: collection
    name: "eventos"
    label: "Eventos"
    path: "_eventos"
    slug: "{{date | date: '%Y-%m-%d'}}-{{title | slugify}}"
    items:
      - name: "layout"
        label: "Layout"
        type: "hidden"
        default: "post"
      - name: "title"
        label: "Título"
        type: "string"
      - name: "date"
        label: "Fecha"
        type: "date"
      - name: "image"
        label: "Imagen"
        type: "image"
      - name: "body"
        label: "Descripción"
        type: "rich-text"