backend:
  name: github
  repo: cobranzalegalcondominio-ops/ateneomaracay # Tu nombre de repo
  branch: main

media_folder: "assets" # Donde se guardarán tus fotos
public_folder: "assets"

collections:
  - name: "eventos"
    label: "Eventos"
    folder: "eventos"
    create: true
    fields:
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Fecha", name: "date", widget: "datetime"}
      - {label: "Contenido", name: "body", widget: "markdown"}
