backend:
  name: github
  repo: cobranzalegalcondominio-ops/ateneomaracay # Tu repositorio
  branch: main
  base_url: https://cobranzalegalcondominio-ops.github.io # Esto soluciona el bloqueo

media_folder: "assets"
public_folder: "assets"

collections:
  - name: "eventos"
    label: "Eventos"
    folder: "eventos"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Fecha", name: "date", widget: "datetime"}
      - {label: "Contenido", name: "body", widget: "markdown"}
